from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def create_presentation():
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "The Evolution of Number Systems"
    subtitle.text = "From Tally Marks to Quantum Computing\nGenerated by AI"
    
    # Content slides data
    slides_data = [
        {
            "title": "What is a Number System?",
            "content": [
                "A mathematical notation for representing numbers.",
                "Provides a unique representation for every standard number.",
                "Represents algebraic and arithmetic structure.",
                "Base (Radix) determines how many digits are used (e.g., Base 10 uses 0-9)."
            ]
        },
        {
            "title": "The Dawn of Counting: Tally Marks",
            "content": [
                "Earliest known method of counting.",
                "Ishango Bone (circa 20,000 BC) displays tally marks.",
                "Unary numeral system (Base 1).",
                "Simple but inefficient for large numbers."
            ]
        },
        {
            "title": "Sumerian & Babylonian System (Base 60)",
            "content": [
                "Developed around 3100 BC.",
                "Sexagesimal system (Base 60).",
                "First known positional numeral system.",
                "Legacy: 60 seconds in a minute, 60 minutes in an hour, 360 degrees in a circle."
            ]
        },
        {
            "title": "Egyptian Numerals (Base 10)",
            "content": [
                "Emerged around 3000 BC.",
                "Base 10, but not a positional system.",
                "Used distinct hieroglyphs for 1, 10, 100, 1000, etc.",
                "Numbers were formed by combining these symbols additively."
            ]
        },
        {
            "title": "Chinese Numerals",
            "content": [
                "Originated during the Shang Dynasty (approx. 1500 BC).",
                "Decimal system using distinct characters.",
                "Later developed rod calculus for complex calculations.",
                "Introduced the concept of positional values long before the West."
            ]
        },
        {
            "title": "Roman Numerals",
            "content": [
                "Originated in ancient Rome (circa 800 BC).",
                "Based on letters of the alphabet (I, V, X, L, C, D, M).",
                "Additive and subtractive notation (e.g., IV = 4, VI = 6).",
                "Lacked a zero, making complex arithmetic very difficult.",
                "Still used today for clocks, book parts, and movie sequels."
            ]
        },
        {
            "title": "Mayan Numerals (Base 20)",
            "content": [
                "Vigesimal system (Base 20).",
                "Used only three symbols: shell (0), dot (1), and bar (5).",
                "Independently developed the concept of zero around 36 BC.",
                "Highly advanced for its time, used for complex astronomical calculations."
            ]
        },
        {
            "title": "Hindu-Arabic Numeral System",
            "content": [
                "The foundation of the modern number system.",
                "Developed in India between the 1st and 4th centuries.",
                "Base 10 (decimal) positional system.",
                "Introduced the modern concept and symbol for zero (0).",
                "Transmitted to the West via Arab mathematicians like Al-Khwarizmi."
            ]
        },
        {
            "title": "The Revolutionary Concept of Zero",
            "content": [
                "Not just a placeholder, but a number with its own value.",
                "Transformed mathematics, allowing for negative numbers and algebra.",
                "Essential for calculus and modern physics.",
                "Initially resisted in Europe due to philosophical and religious reasons."
            ]
        },
        {
            "title": "Binary Number System (Base 2)",
            "content": [
                "Uses only two digits: 0 and 1.",
                "Formalized by Gottfried Wilhelm Leibniz in 1689.",
                "The foundation of all modern computing and digital electronics.",
                "Represents logic states: True (1) and False (0)."
            ]
        },
        {
            "title": "Hexadecimal System (Base 16)",
            "content": [
                "Uses 16 distinct symbols: 0-9 and A-F.",
                "Widely used in computer science.",
                "Provides a human-friendly representation of binary-coded values.",
                "Used for memory addresses, color codes (e.g., #FFFFFF), and IPv6."
            ]
        },
        {
            "title": "Summary & Future: Quantum Computing",
            "content": [
                "Number systems evolved to meet societal needs.",
                "From tallying sheep to complex digital physics.",
                "Next frontier: Qubits (Quantum bits) that can be 0, 1, or both simultaneously.",
                "The journey of numbers is the journey of human civilization."
            ]
        }
    ]
    
    # Add slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_data in slides_data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data["title"]
        
        tf = body_shape.text_frame
        for i, point in enumerate(slide_data["content"]):
            if i == 0:
                tf.text = point
            else:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
                
    # Save the presentation
    file_path = "The_Evolution_of_Number_System.pptx"
    prs.save(file_path)
    print(f"Presentation generated successfully: {file_path}")

if __name__ == '__main__':
    create_presentation()
